### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by DumbChester** [CLADevs/VanillaX#48]
Main Issues (Phar disabled) :
Trying to register previously registered Blocks when doing /reload

Ver used. LatestCommit
PMMP : 3.21
PHP: 7.4

SIDE ISSUES (Playable) : 
- (Incompatability with MultiWorld 1.5.3 - Gamerule Errors / Internal Corruption happening )
- Minecart not functioning and Unbreakable after placed (might be due to plugin disabled then placed) . 

Suggestions:
-ShulkerBox, Sound
-Gamemode Alias /gm
-Skin loading Error

Thankyou so much, Super love your plugin sorry for the inconvenience.

**Comment by MonoAdrian23** [comment]
Never do /reload!

**Comment by DumbChester** [comment]
Gotcha.

**Comment by xXNiceYT** [comment]
1. Yeah restarted server completely rather than reloading.
2. This plugin isn’t compatible with mute world, Go into Config and toggle gamerule to false in feature column.
3. Minecart s aren’t implemented 
4. Shucker box are added and I don’t get what you mean by “sound” 
5. I am trying to make it vanilla like lol not adding aliases 
6. Skin loading error? What do you mean by that, never had it

**Comment by MonoAdrian23** [comment]
Skin Loading is a problem by Pocketmine. 
He mean this single colored skins. 
But this is a Pocketmine Issue

**Comment by xXNiceYT** [comment]
I’ll check on it when I get the chance to

**Comment by DumbChester** [comment]
i meant when opening shulker Boxes it doesn't play a opening /closing sound (might be on my end)

And yeah If it was a Pocketmine Error the skin You can close thia now just a suggesttion, Thanks.

**Comment by xXNiceYT** [comment]
Alright I’ll check into it later
